plugin: aws_ec2

regions:
  - ap-south-1

keyed_groups:
  - key: tags.Environment
    prefix: ""
    separator: ""

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ~/.ssh/my-keypair.pem
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

filters:
  instance-state-name: running

